### PR TITLE
feat: version 1.21

### PR DESCRIPTION
**Pull request by atomic-junky**
Support for directory name changes:
```
structures -> structure
advancements -> advancement
recipes -> recipe
loot_tables -> loot_table
predicates -> predicate
item_modifiers ->item_modifier
functions -> function
tags/functions -> tags/function
tags/items-> tags/item
tags/blocks-> tags/block
tags/entity_types -> tags/entity_type
tags/fluids -> tags/fluid
tags/game_events-> tags/game_event
```

### CODE REVIEW

**Comment by TheNuclearNexus** [comment]
These changes break the ability to load packs made for older versions of Minecraft completely
Also, according to the wiki only tags/functions was changed, other tags were unaffected

**Comment by atomic-junky** [comment]
That's not what I understood, I saw it in the wiki too

**Comment by TheNuclearNexus** [comment]
Ah ok must have missed it, do you know which snapshot it was?

**Comment by atomic-junky** [comment]
It seams to be 24w19a according to this video of slicelime https://www.youtube.com/watch?v=AJTSOwlsgwk

**Comment by RitikShah** [comment]
Superceded by 1.21 support (#422)

**Pull request closed without merging**
